# fly.toml file

app = "server-passthrough"

kill_signal = "SIGINT"
kill_timeout = 5

[env]

[[services]]
  internal_port = 5000
  protocol = "udp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.udp_checks]]
    interval = 10000
    timeout = 2000
