# fly.toml file

app = "server-passthrough"

kill_signal = "SIGINT"
kill_timeout = 5

[env]

[[services]]
  internal_port = 5000
  protocol = "udp"

  [[services.ports]]
    port = "5000"

[[services]]
  internal_port = 5000
  protocol = "tcp"

  [[services.ports]]
    port = "5000"
